server:
  port: 8050
spring:
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer/**
          filters:
            - RewritePath=/customer/(?<segment>.*), /$\{segment}
        - id: order
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - RewritePath=/order/(?<segment>.*), /$\{segment}
        - id: product
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
          filters:
            - RewritePath=/product/(?<segment>.*), /$\{segment}
        - id: shopping-cart
          uri: lb://SHOPPING-CART-SERVICE
          predicates:
            - Path=/cart/command/**
          filters:
            - RewritePath=/cart/command/(?<segment>.*), /$\{segment}
