server:
  port: 8083
spring:
  data:
    mongodb:
      uri: mongodb://localhost/shopping-cart
      database: shopping-cart
  kafka:
    producer:
      properties:
        acks: 1
        spring:
          json:
            add:
              type:
                headers: false
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
